### ISSUE TITLE
Support for ghidra

### ISSUE THREAD

**Issue by asmjmp0** [lifting-bits/anvill#161]
Can it support for ghidra?

**Comment by pgoodman** [comment]
Not yet but @Toiz has been looking into this.

**Comment by TheFrozenDuck** [comment]
Is there any progress regarding this topic? It would be nice to have an open-source solution working with this project.

**Comment by pgoodman** [comment]
Ping @Toizi.

**Comment by Toizi** [comment]
Hi @TheFrozenDuck and @pgoodman 
At this point I have mostly given up on trying to add Ghidra support.

I haven't touched the project in a while but from what I can remember there were some limitations that just made it unusable in practice.
1. Ghidra uses Jython, which is python2 on the JVM. Since anvill is python3, I used the [ghidra_bridge project](https://github.com/justfoxing/ghidra_bridge) for compatibility. While ghidra_bridge is a nice project, it requires some workarounds that make using the ghidra API harder than it should be.
2. Ghidra is not great for using it like a library/api to analyze some code. While the option to use it as headless analyzer exists, it's a lot of work to just run some script with it. Especially when comparing it to something like binary ninja.
The current approach to get the tests running (see [here](https://github.com/Toizi/anvill/blob/a6a78774ffd514b964725dd72bb4c92a4845e981/tools/decompile-json/tests/scripts/roundtrip.py#L167)) takes care of launching a headless instance, specifying a script so Ghidra performs a full decompilation, followed by executing the ghidra_bridge script so that it waits for a connection from anvill, executes anvill and then tries to save a log of what happened.
All of that uses ugly timeouts and it might happen that some process did not terminate properly and needs to be killed but it didn't kill the child processes, etc. It's just super ugly but I don't think there is a much better way to do it.
3. Everything is slow. The whole external process with RPC setup plus the fact that for type information, the "Decompiler Parameter ID" needs to be run, which means Ghidra will need to decompile the whole program. This can take a long time. Just the simple tests in `roundtrip.py` take several minutes to run on Ghidra.

Overall, using it was just such a bad experience that I decided to drop it. It might be a bit better if it's integrated as a plugin like it has been done for IDA, but the development and automated test setup will still suck.

If anyone wants to continue, feel free to take a loot at my progress [here](https://github.com/Toizi/anvill/tree/ghidra_spec_file_gen). Quite a few of the roundtrip tests worked back when I tried it.
Broken tests were
- assert.c
- branch.c
- funcptr.c
- loop.c
- nested_struct.c
- sum.c

I just added a WIP commit so the roundtrip tests are hardcoded to use Ghidra in my fork for anyone looking to get started.
The only requirement for the setup from what I can remember is
- setting the environment variable `GHDIRA_PATH` to point to your Ghidra installation
- Installing the ghidra_bridge scripts in `$HOME/ghidra_scripts`
- 
Both of those requirements are in the code though so it should error out with a helpful message if the setup is wrong.

If anything is unclear, feel free to reach out and I'll try my best to help.

**Comment by asmjmp0** [comment]
I will close the issue, thank you so much for your time.
